using Acme.StudentManagementSystem.EntityFrameworkCore;
using Xunit;

namespace Acme.StudentManagementSystem.EntityFrameworkCore;

public class StudentManagementSystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<StudentManagementSystemEntityFrameworkCoreFixture>
{

}
